import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parse } from 'yaml';
import type { HandoffReason } from '../types/index.js';
import { now } from './create.js';
import { fingerprint } from './derive.js';
import { findPlanId, getPlanDir } from './resolver.js';
import { readState, updateState } from './state.js';

export async function createCheckpoint(
  projectRoot: string,
  planId: string | undefined,
  reason: HandoffReason
): Promise<string> {
  const id = findPlanId(projectRoot, planId);
  const planDir = getPlanDir(projectRoot, id);
  // Defensive: protects against unsafe callers using `as HandoffReason`
  const validReasons: HandoffReason[] = ['pause', 'transfer', 'completion'];
  if (!validReasons.includes(reason)) {
    throw new Error(
      `Invalid handoff reason: ${reason}. Must be one of: pause, transfer, completion`
    );
  }

  // Check plan is in REVIEWED state
  const state = readState(planDir);
  if (state.state !== 'REVIEWED') {
    throw new Error(
      `Cannot create checkpoint: plan is in state '${state.state}', must be 'REVIEWED'`
    );
  }

  const planPath = join(planDir, 'plan.md');
  const reviewPath = join(planDir, 'review-report.md');

  if (!existsSync(planPath)) throw new Error(`plan.md not found`);
  if (!existsSync(reviewPath)) throw new Error(`review-report.md not found`);

  // Verify fingerprint coherency before creating checkpoint
  const planContent = readFileSync(planPath, 'utf-8');
  const currentFp = fingerprint(planContent);
  const yamlPath = join(planDir, 'plan.yaml');
  if (!existsSync(yamlPath)) throw new Error(`plan.yaml not found. Run \`plan derive\` first.`);
  const yamlContent = readFileSync(yamlPath, 'utf-8');
  const yamlParsed = parse(yamlContent);
  const storedFp = yamlParsed?.source_md_fingerprint as string | undefined;
  if (storedFp && storedFp !== currentFp) {
    throw new Error(
      `fingerprint mismatch: plan.md (${currentFp}) does not match plan.yaml source fingerprint (${storedFp}). Re-run \`plan derive\`.`
    );
  }

  const reviewContent = readFileSync(reviewPath, 'utf-8');
  // Read validation report
  const validationPath = join(planDir, 'validation-report.yaml');
  if (!existsSync(validationPath)) throw new Error(`validation-report.yaml not found`);
  const validationContent = readFileSync(validationPath, 'utf-8');

  // Generate checkpoint markdown
  const nowDate = new Date();
  const date = nowDate.toISOString().split('T')[0];
  const time = nowDate.toTimeString().substring(0, 8).replace(/:/g, '');
  const checkpointName = `checkpoint_${time}_${id}.md`;

  const checkpointDir = join(projectRoot, '_ctx', 'checkpoints', date);
  if (!existsSync(checkpointDir)) {
    mkdirSync(checkpointDir, { recursive: true });
  }

  const checkpointPath = join(checkpointDir, checkpointName);

  const completedTasks = ['authoring', 'validation', 'review'];
  const pendingTasks: string[] = [];
  const pendingErrors: string[] = [];
  const nextAgentPrompt = `Continue with plan '${id}'. Review report: ${reviewContent.substring(0, 500)}...`;

  const checkpointMd = `# Checkpoint: ${id}
Date: ${now()}

## Handoff Reason
${reason}

## Plan State
${state.state}

## Completed Tasks
${completedTasks.map((t) => `- ${t}`).join('\n')}

## Pending Tasks
${pendingTasks.length > 0 ? pendingTasks.map((t) => `- ${t}`).join('\n') : 'None'}

## Pending Errors
${pendingErrors.length > 0 ? pendingErrors.map((e) => `- ${e}`).join('\n') : 'None'}

## Next Agent Prompt
 ${nextAgentPrompt}
 
## Current Plan
${planPath}

## Validation Report
${validationContent}

---
Generated by plan_dope v0.1.0
`;

  writeFileSync(checkpointPath, checkpointMd, 'utf-8');

  // Update state
  updateState(planDir, 'HANDOFF_READY');

  return checkpointPath;
}
